sudo: true
os: trusty
cache: false
env:
  global:
    - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - coreId=core@0.1.0-1
    - logicId=logic@0.1.0-2
    - uiId=ui@0.1.0-1
    - securityId=security@0.1.0-1
before_install:
- openssl aes-256-cbc -K $encrypted_a16ae3ec4b79_key -iv $encrypted_a16ae3ec4b79_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a HubOrg
- sfdx force:auth:jwt:grant -i $SBOXCONSUMERKEY -f assets/server.key -r https://test.salesforce.com -u $SBOXUSERNAME
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a pkgInstallOrg -w 10
- sfdx force:org:display -u pkgInstallOrg
- sfdx force:package:install -k packagepwd -p $coreId -s AllUsers -w 60
- sfdx force:package:install -k packagepwd -p $logicId -s AllUsers -w 60
- sfdx force:package:install -k packagepwd -p $uiId -s AllUsers -w 60
- echo 'y' | sfdx force:package:install -k packagepwd -p $securityId -s AllUsers -w 60
- sfdx force:apex:test:run -u pkgInstallOrg -r human -w 10
- sfdx force:org:delete -u pkgInstallOrg -p

# Push packages to Sandbox
- sfdx force:package:install -k packagepwd -u $SBOXUSERNAME -p $coreId -s AllUsers -w 60
- sfdx force:package:install -k packagepwd -u $SBOXUSERNAME -p $logicId -s AllUsers -w 60
- sfdx force:package:install -k packagepwd -u $SBOXUSERNAME -p $uiId -s AllUsers -w 60
- echo 'y' | sfdx force:package:install -k packagepwd -u $SBOXUSERNAME -p $securityId -s AllUsers -w 60